[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  PULSE_REPORT_DIR = "pulse-report"
  PULSE_USER_CWD = "."

[dev]
  command = "npm run pulse-dashboard"
  port = 9002
  targetPort = 9002

[[plugins]]
  package = "@netlify/plugin-nextjs"
